export * from "./queries/about";
export * from "./queries/catalog";
export * from "./queries/connections";
export * from "./queries/home";
export * from "./queries/macrothemes";
export * from "./queries/panels";
export * from "./queries/posts";
export * from "./queries/boletim";
export * from "./queries/search";
