name: CI/CD DataNordeste

on:
  push:
    branches: ["main-v2"]

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update docker metadata with the tag 
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ vars.DOCKER_IMAGE_BETA }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          file: Dockerfile.production
          labels: ${{ steps.meta.outputs.labels }}
          tags: |
            ${{ vars.DOCKER_IMAGE_BETA }}:main-v2
            ${{ steps.meta.outputs.tags }}
          build-args: |
            NEXT_PUBLIC_CONTENTFUL_SPACE=${{ secrets.NEXT_PUBLIC_CONTENTFUL_SPACE  }}
            NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN=${{ secrets.NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN }}
            NEXT_PUBLIC_HOST_URL=${{ vars.NEXT_PUBLIC_HOST_URL }}
            NEXT_PUBLIC_GA_ID=${{ secrets.NEXT_PUBLIC_GA_ID }}

  push-beta:
    needs: build-image
    runs-on: beta-runner
    steps:
      - name: Pull the latest image
        run: sudo docker pull ${{ vars.DOCKER_IMAGE_BETA }}:main-v2

      - name: Stop existing container
        run: sudo docker rm -f data-nordeste-frontend-app-v2 || true 
            
      - name: Run new container
        run: sudo docker run --name data-nordeste-frontend-app-v2 -p 3001:${{ vars.CONTAINER_PORT }} -d ${{ vars.DOCKER_IMAGE_BETA }}:main-v2

      # - name: Connect to network
      #   run: docker network connect ${{ vars.NETWORK_NAME }} data-nordeste-frontend-app-v2

      - name: Prune unused Docker images
        run: sudo docker system prune -f
